version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "server"
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    labels:
      - "client"
      - "dependencies"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
