[package]
name = "blackhole"
version = "0.1.0"
edition = "2021"

[lib]
name = "blackhole"
path = "lib/src.rs"

[[bin]]
name = "blackhole"
path = "src/main.rs"

[[bench]]
name = "benchmarks"
harness = false

[dependencies]
criterion = { version = "0.3", features = [ "real_blackbox", "html_reports" ] }
num = "0.4"
opentelemetry = { version = "0.17", features = [ "rt-tokio" ] }
serde_json = "1"
thiserror = "1"
tokio = { version = "1", features = [ "net", "macros", "rt-multi-thread", "tracing" ] }
tracing = "0.1"
tracing-opentelemetry = "0.17"
tracing-subscriber = { version = "0.3", features = [ "default", "env-filter" ] }
warp = "0.3"

[profile.release]
lto = "thin"
opt-level = 2
strip = "symbols"
