[package]
name = "blackhole"
version = "0.2.0"
edition = "2021"
publish = false

[lib]
name = "blackhole"
path = "lib/src.rs"

[[bin]]
name = "blackhole"
path = "src/main.rs"

[[bench]]
name = "benchmarks"
harness = false

[dependencies]
chrono = { version = "0.4", features = [ "serde" ] }
criterion = { version = "0.4", features = [ "real_blackbox", "html_reports" ] }
lazy_static = "1"
num = "0.4"
opentelemetry = { version = "0.18", features = [ "rt-tokio" ] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tokio = { version = "1", features = [ "net", "macros", "parking_lot", "rt-multi-thread", "tracing" ] }
tracing = "0.1"
tracing-opentelemetry = "0.17"
tracing-subscriber = { version = "0.3", features = [ "default", "env-filter" ] }
warp = "0.3"

[profile.release]
lto = true
opt-level = 2
strip = "symbols"
codegen-units = 1
panic = "abort"
