[package]
name = "blackhole"
version = "0.4.0"
edition = "2021"
publish = false

[lib]
name = "blackhole"
path = "lib/src.rs"

[[bin]]
name = "blackhole"
path = "src/main.rs"

[[bench]]
name = "benchmarks"
harness = false

[dependencies]
async-trait = "0.1"
chrono = { version = "0.4", default-features = false, features = [ "clock", "serde" ] }
chumsky = "0.8"
clap = { version = "4" , features = [ "derive" ] }
criterion = { version = "0.4", default-features = false, features = [ "html_reports", "plotters", "real_blackbox" ] }
num = { version = "0.4", default-features = false }
opentelemetry = { version = "0.18", default-features = false, features = [ "rt-tokio" ] }
reqwest = { version = "0.11", features = [ "brotli", "gzip" ] }
serde = { version = "1", default-features = false, features = [ "derive" ] }
serde_json = "1"
thiserror = "1"
tokio = { version = "1", default-features = false, features = [ "net", "macros", "parking_lot", "rt-multi-thread", "tracing" ] }
toml = "0.5"
tracing = { version = "0.1", default-features = false, features = [ "attributes", "std" ] }
tracing-opentelemetry = "0.18"
tracing-subscriber = { version = "0.3", default-features = false, features =  [ "fmt", "parking_lot", "smallvec", "tracing-log" ] }
warp = { version = "0.3", default-features = false, features = [ "async-compression", "compression"] }

[profile.release]
lto = true
opt-level = 2
strip = "symbols"
codegen-units = 1
panic = "abort"
