[package]
name = "blackhole"
version = "0.1.0"
edition = "2021"

[lib]
name = "blackhole"
path = "lib/src.rs"

[[bin]]
name = "blackhole"
path = "bin/main.rs"

[dependencies]
console-subscriber = "0.1"
opentelemetry = { version = "0.17", features = ["rt-tokio"] }
tokio = { version = "1", features = [ "full", "tracing" ] }
tracing = "0.1"
tracing-opentelemetry = "0.17"
tracing-subscriber = { version = "0.3", features = [ "json" ] }

[profile.release]
lto = "thin"
opt-level = "z"
