keep_logs = 21600

[[upstream]]
ip = "9.9.9.9"
port = 53

[[filter]]
name = "Energized"
url = "https://block.energized.pro/spark/formats/hosts"

[[schedule]]
name = "Filters"
schedule = 21600

[[schedule]]
name = "Logs"
schedule = 21600