name: Benchmarks
on:
  pull_request:
    branches: ["main"]
    # paths:
    #   - "**/*.rs"
    #   - "Cargo.toml"
    #   - "Cargo.lock"

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup toolchain update nightly && rustup default nightly

      - name: Run benchmark
        run: cargo +nightly bench | tee output.txt

      - name: Store Benchmarks
        uses: benchmark-action/github-action-benchmark@v1.14.0
        with:
          name: Rust Benchmark
          tool: "cargo"
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alert-threshold: "150%"
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: "@pyxxil"
