name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag blackhole:latest
      # Would prefer to use the following, or something like it, however it's not working atm
      # run: docker build . --file Dockerfile --tag blackhole:$(git describe --tags --abbrev=0)
