name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '*.md'
      - '.*ignore'
      - 'benches/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '*.md'
      - '.*ignore'
      - 'benches/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag,enable=true
            type=ref,event=branch,enable=true
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}},enable=true

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
