name: Rust

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: rustup toolchain install
      # You may pin to the exact commit or the version.
      # uses: dtolnay/rust-toolchain@1ce4a7352a1efe5dede2e52c75512b34256e4f44
      uses: dtolnay/rust-toolchain@v1
      with:
        # Rust toolchain specification -- see https://rust-lang.github.io/rustup/concepts/toolchains.html#toolchain-specification
        toolchain: nightly
        components: clippy
    - name: Run clippy
      run: cargo clippy
    - name: Run tests
      run: cargo test --verbose
