name: Rust

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: rustup toolchain install
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: nightly
        components: clippy rustfmt

    - name: Ensure style is consistent
      run: cargo fmt --check

    - name: Ensure all possible issues are fixed
      run: cargo clippy --
        -D clippy::pedantic 
        -A clippy::cast_possible_truncation
        -A clippy::must-use-candidate

    - name: Perform testing
      run: cargo test --verbose
